version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=index.py
      - FLASK_ENV=development
      - Mistral_key=${Mistral_key}
      - CoreAPI_KEY=${CoreAPI_KEY}
      - GeminiAPI_KEY=${GeminiAPI_KEY}